#pragma config(Sensor, S1,     touch,          sensorI2CMuxController)
#pragma config(Sensor, S2,     sound,          sensorNone)
#pragma config(Sensor, S3,     light,          sensorNone)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c"





#define B_BUTTON 3



void moveR(){
	getJoystickSettings(joystick);
   do {
     	if (joy1Btn(B_BUTTON) == true){
   motor[rightMotor] = 200;
 }
  else {
   motor[rightMotor] = 0;
 }
 	getJoystickSettings(joystick);
 } while(joy1Btn(B_BUTTON) == true);
}








#define X_BUTTON 1


void moveL(){
	getJoystickSettings(joystick);

	do
	{
		if (joy1Btn(X_BUTTON) == true)
		{
		 	motor[leftMotor] = 200;
		}
		else
		{
			motor[leftMotor] = 0;
		}
	getJoystickSettings(joystick);

} while(joy1Btn(X_BUTTON) == true);
}







#define Y_BUTTON 4


void moveS(){
	getJoystickSettings(joystick);
	do {
	if (joy1Btn(Y_BUTTON) == true){
	 motor[leftMotor] = 200;
	 motor[rightMotor] = 200;
}
	else {
		motor[leftMotor] = 0;
		motor[rightMotor] = 0;
}
	getJoystickSettings(joystick);
} while(joy1Btn(Y_BUTTON) == true);
}








#define A_BUTTON 2


void moveB(){
	getJoystickSettings(joystick);
	do {
	if (joy1Btn(A_BUTTON) == true){
	 motor[leftMotor] = -200;
	 motor[rightMotor] = -200;
}
	else {
		motor[leftMotor] = 0;
		motor[rightMotor] = 0;
}
	getJoystickSettings(joystick);
} while(joy1Btn(A_BUTTON) == true);
}
