#pragma config(Sensor, in1,    lightSensor,         sensorLineFollower)
#pragma config(Sensor, dgtl1,  rightEncoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  compassSensor,       sensorVirtualCompass)
#pragma config(Sensor, dgtl6,  touchSensor,         sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,         sensorSONAR_inch)
#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop)
#pragma config(Motor,  port6,           gripper,       tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//	This setup is for the SQUAREBOT	model, if you are using the SWERVEBOT model, please set motor port3 to reversed instead	of motor port2.

/************************************\
|*  ROBOTC Virtual World Template   *|
|*                                  *|
|*  DO NOT OVERWRITE THIS FILE      *|
|*  MAKE SURE TO "SAVE AS" INSTEAD  *|
\************************************/

#include "JoystickDriver.c"


float Ease(float i)
{
	i /= 137;
	if(i > 0)
	i *= i;
	else
	i *= -i;

	i *= 137;
	return i;
}

void Joystick()
{
	getJoystickSettings(joystick);
	float leftSpeed, rightSpeed;
	leftSpeed = Ease(joystick.joy1_y1);
	rightSpeed = Ease(joystick.joy1_y1);
	motor[leftMotor] = leftSpeed;
	motor[rightMotor] = rightSpeed;
}


#define X_BUTTON 1



void moveR(){
	getJoystickSettings(joystick);
   do {
     	if (joy1Btn(X_BUTTON) == true){
   motor[rightMotor] = 100;
 }
  else {
   motor[rightMotor] = 0;
 }
 	getJoystickSettings(joystick);
 } while(joy1Btn(X_BUTTON) == true);
}








#define B_BUTTON 3


void moveL(){
	getJoystickSettings(joystick);

	do
	{
		if (joy1Btn(B_BUTTON) == true)
		{
		 	motor[leftMotor] = 100;
		}
		else
		{
			motor[leftMotor] = 0;
		}
	getJoystickSettings(joystick);

} while(joy1Btn(B_BUTTON) == true);
}







#define Y_BUTTON 4


void moveS(){
	getJoystickSettings(joystick);
	do {
	if (joy1Btn(Y_BUTTON) == true){
	 motor[leftMotor] = 100;
	 motor[rightMotor] = 100;
}
	else {
		motor[leftMotor] = 0;
		motor[rightMotor] = 0;
}
	getJoystickSettings(joystick);
} while(joy1Btn(Y_BUTTON) == true);
}








#define A_BUTTON 2


void moveB(){
	getJoystickSettings(joystick);
	do {
	if (joy1Btn(A_BUTTON) == true){
	 motor[leftMotor] = -100;
	 motor[rightMotor] = -100;
}
	else {
		motor[leftMotor] = 0;
		motor[rightMotor] = 0;
}
	getJoystickSettings(joystick);
} while(joy1Btn(A_BUTTON) == true);
}







task main()
{

while(true)
{
//moveB();
//moveL();
//moveR();
//moveS();
Joystick();
}

}
