#include "JoystickDriver.c"
#pragma config(Sensor, in1,    lightSensor,         sensorLineFollower)
#pragma config(Sensor, dgtl1,  rightEncoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  compassSensor,       sensorVirtualCompass)
#pragma config(Sensor, dgtl6,  touchSensor,         sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,         sensorSONAR_inch)
#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop)
#pragma config(Motor,  port6,           gripper,       tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//	This setup is for the SQUAREBOT	model, if you are using the SWERVEBOT model, please set motor port3 to reversed instead	of motor port2.

/************************************\
|*  ROBOTC Virtual World Template   *|
|*                                  *|
|*  DO NOT OVERWRITE THIS FILE      *|
|*  MAKE SURE TO "SAVE AS" INSTEAD  *|
\************************************/



#define MIN_JOYSTICK_MOVEMENT 10




#define B_BUTTON 3



int getRightStickX()
{
	getJoystickSettings(joystick);
	return joystick.joy1_x2;
}

int getRightStickY()
{
	getJoystickSettings(joystick);
	return joystick.joy1_y2;
}

int getLeftStickX()
{
	getJoystickSettings(joystick);
	return joystick.joy1_x1;
}

int getLeftStickY()
{
	getJoystickSettings(joystick);
	return joystick.joy1_y1;
}



bool RightStickMove()
{
	if(getRightStickY() > MIN_JOYSTICK_MOVEMENT)
	{
		motor[port2] = getRightStickY();
	}
}

bool LeftStickMove()
{
	getJoystickSettings(joystick);
	if(getLeftStickY() > 0)
	{
		if(getLeftStickY() > MIN_JOYSTICK_MOVEMENT)
		{
			motor[port3] = getLeftStickY();
			return true;
		}
	}
	else
	{
		if(getLeftStickY() < MIN_JOYSTICK_MOVEMENT)
		{
			motor[port3] = getLeftStickY();
			return true;
		}
	}
	return false;
}






void moveR(){
	getJoystickSettings(joystick);
   do {
     	if (joy1Btn(B_BUTTON) == true){
   motor[port3] = 200;
 }
  else {
   motor[port3] = 0;
 }
 	getJoystickSettings(joystick);
 } while(joy1Btn(B_BUTTON) == true);
}








#define X_BUTTON 1


void moveL(){
	getJoystickSettings(joystick);

	do
	{
		if (joy1Btn(X_BUTTON) == true)
		{
		 	motor[port2] = 200;
		}
		else
		{
			motor[port2] = 0;
		}
	getJoystickSettings(joystick);

} while(joy1Btn(X_BUTTON) == true);
}







#define Y_BUTTON 4


void moveS(){
	getJoystickSettings(joystick);
	do {
	if (joy1Btn(Y_BUTTON) == true){
	 motor[port2] = 200;
	 motor[port3] = 200;
}
	else {
		motor[port2] = 0;
		motor[port3] = 0;
}
	getJoystickSettings(joystick);
} while(joy1Btn(Y_BUTTON) == true);
}








#define A_BUTTON 2


void moveB(){
	getJoystickSettings(joystick);
	do {
	if (joy1Btn(A_BUTTON) == true){
	 motor[port2] = -200;
	 motor[port3] = -200;
}
	else {
		motor[port2] = 0;
		motor[port3] = 0;
}
	getJoystickSettings(joystick);
} while(joy1Btn(A_BUTTON) == true);
}







task main(){

while(true) {
 moveR();
 moveL();
 moveS();
 moveB();
 RightStickMove();
 LeftStickMove();
}

}
