#include "JoystickDriver.c"
#pragma config(Sensor, in1,    lightSensor,         sensorLineFollower)
#pragma config(Sensor, dgtl1,  rightEncoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  compassSensor,       sensorVirtualCompass)
#pragma config(Sensor, dgtl6,  touchSensor,         sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,         sensorSONAR_inch)
#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop)
#pragma config(Motor,  port6,           gripper,       tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//	This setup is for the SQUAREBOT	model, if you are using the SWERVEBOT model, please set motor port3 to reversed instead	of motor port2.

/************************************\
|*  ROBOTC Virtual World Template   *|
|*                                  *|
|*  DO NOT OVERWRITE THIS FILE      *|
|*  MAKE SURE TO "SAVE AS" INSTEAD  *|
\************************************/

void move(int thingy, int speed, int duration)
{
	if(thingy == 1)
	{
		motor[port2] = speed;
		motor[port3] = speed;
	}
	if(thingy == 2)
	{
		motor[port2] = -speed;
		motor[port3] = -speed;
	}
	if(thingy == 3)
		{
			motor[port2] = speed;
			motor[port3] = -speed;
		}
	if(thingy == 4)
		{
			motor[port2] = -speed;
			motor[port3] = speed;
		}
	wait1Msec(duration);
}


task main()
{

	// your code goes here
	move(1, 100, 4500);
	move(4, 80, 700);
	move(1, 100, 4500);
	move(4, 80, 700);
	move(1, 100, 4500);
	move(4, 80, 700);
	move(1, 100, 4500);
	move(4, 80, 700);
}
