#pragma config(Sensor, in1,    lightSensor,         sensorLineFollower)
#pragma config(Sensor, dgtl1,  rightEncoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  compassSensor,       sensorVirtualCompass)
#pragma config(Sensor, dgtl6,  touchSensor,         sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,         sensorSONAR_inch)
#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop)
#pragma config(Motor,  port6,           gripper,       tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//	This setup is for the SQUAREBOT	model, if you are using the SWERVEBOT model, please set motor port3 to reversed instead	of motor port2.

/************************************\
|*  ROBOTC Virtual World Template   *|
|*                                  *|
|*  DO NOT OVERWRITE THIS FILE      *|
|*  MAKE SURE TO "SAVE AS" INSTEAD  *|
\************************************/

#include "JoystickDriver.c"



//kjgaherygotauj;ghoiaerghifobgyahnrk/lghaokyq

/*
*s;ooooooooooihoazi/'ghyrelkagisshisurrrrrrrr;8g.tfuruqie5ierlnyyotyoyoyyuy4yoi48605m A<vs\  G RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6 RT6
*/

#define B_BUTTON 3



void moveR(){
	getJoystickSettings(joystick);
   do {
     	if (joy1Btn(B_BUTTON) == true){
   motor[leftMotor] = 100;
 }
  else {
   motor[leftMotor] = 0;
 }
 	getJoystickSettings(joystick);
 } while(joy1Btn(B_BUTTON) == true);
}








#define X_BUTTON 1


void moveL(){
	getJoystickSettings(joystick);

	do
	{
		if (joy1Btn(X_BUTTON) == true)
		{
		 	motor[rightMotor] = 100;
		}
		else
		{
			motor[rightMotor] = 0;
		}
	getJoystickSettings(joystick);

} while(joy1Btn(X_BUTTON) == true);
}







#define Y_BUTTON 4


void moveS(){
	getJoystickSettings(joystick);
	do {
	if (joy1Btn(Y_BUTTON) == true){
	 motor[leftMotor] = 100;
	 motor[rightMotor] = 100;
}
	else {
		motor[leftMotor] = 0;
		motor[rightMotor] = 0;
}
	getJoystickSettings(joystick);
} while(joy1Btn(Y_BUTTON) == true);
}








#define A_BUTTON 2


void moveB(){
	getJoystickSettings(joystick);
	do {
	if (joy1Btn(A_BUTTON) == true){
	 motor[leftMotor] = -100;
	 motor[rightMotor] = -100;
}
	else {
		motor[leftMotor] = 0;
		motor[rightMotor] = 0;
}
	getJoystickSettings(joystick);
} while(joy1Btn(A_BUTTON) == true);
}

double Ease(double i)
{
	return i * i;
}

void Joystick()
{
	getJoystickSettings(joystick);
	int leftSpeed, rightSpeed;
	leftSpeed = Ease((joy1_y2)/100) * 100;
	rightSpeed = Ease((joy1_y1)/100) * 100;
	motor[leftMotor] = leftSpeed;
	motor[rightMotor] = rightSpeed;
}




task main()
{

while(true)
{
	moveR();
	moveL();
	moveS();
	moveB();
	Joystick();
}

}
